### ISSUE TITLE
How to install? 

### ISSUE THREAD

**Issue by DeanKamali** [sebakerckhof/meteor-method-hooks#3]
I haven't been able to find this package on atmospherejs, how can I go about adding "meteor-method-hooks" to my project? 

Thanks

**Comment by DeanKamali** [comment]
Found it as `seba:method-hooks ` 
Many thanks

**Comment by sebakerckhof** [comment]
It's called `seba:method-hooks`. So you can run: `meteor add seba:method-hooks`

**Comment by sebakerckhof** [comment]
ah, just too late ;)

**Comment by DeanKamali** [comment]
you provided complete answer! so thanks again : D
